### ISSUE TITLE
体验不好，如果页面内容比较多，出现滚动条，tabs也跟着滚动了

### ISSUE THREAD

**Issue by chifangxiong** [yunsii/ant-design-pro-plus#28]
![image](https://user-images.githubusercontent.com/56291011/153702025-ec2d009b-6f25-4a66-8e69-928f1ab29be7.png)

**Comment by yunsii** [comment]
看样子你是直接使用的 use-switch-tabs 包？你说的问题在应用层面做样式覆盖即可。

**Comment by chifangxiong** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by chifangxiong** [comment]
> 看样子你是直接使用的 use-switch-tabs 包？你说的问题在应用层面做样式覆盖即可。

defaultSettings.ts有用到了use-switch-tabs，你的项目正常install完，启动报错起不来，然后我自己弄了一个新的ant design pro项目，把你项目相关tabs的文件拷贝过来，然后就长我发的图片那样了，我是前端菜鸟，哈

**Comment by chifangxiong** [comment]
![image](https://user-images.githubusercontent.com/56291011/153703016-32142bf2-712d-4b2e-9ea1-f9e6ef598f77.png)
项目启动报错
