### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by chifangxiong** [yunsii/ant-design-pro-plus#29]
![image](https://user-images.githubusercontent.com/56291011/153703016-32142bf2-712d-4b2e-9ea1-f9e6ef598f77.png)
项目启动报错

_Originally posted by @chifangxiong in https://github.com/yunsii/ant-design-pro-plus/issues/28#issuecomment-1037056682_

**Comment by yunsii** [comment]
你是用 yarn 安装的依赖吗？

**Comment by chifangxiong** [comment]
是的，npm也试了，都报同一个错
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月12日(星期六) 下午5:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yunsii/ant-design-pro-plus] 项目启动报错 (Issue #29)





 
你是用 yarn 安装的依赖吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yunsii** [comment]
看报错可能跟 umi 的 mfsu 有关？把 https://github.com/yunsii/ant-design-pro-plus/blob/master/config/config.ts#L70 `mfsu: {}` 删除试试呢。

**Comment by chifangxiong** [comment]
删了可以起来，不过页面内容多得话出现滚动条，tabs会滚到顶部看不见
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月12日(星期六) 下午5:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yunsii/ant-design-pro-plus] 项目启动报错 (Issue #29)





 
看报错可能跟 umi 的 mfsu 有关？把 https://github.com/yunsii/ant-design-pro-plus/blob/master/config/config.ts#L70 mfsu: {} 删除试试呢。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yunsii** [comment]
fixed 为 true 的时候，正常 tabs 导航栏是不会动的，内容滚动，可能在迁移 ant design pro v5 的时候没注意样式变化，我晚些时间看看。

**Comment by chifangxiong** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月12日(星期六) 下午5:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yunsii/ant-design-pro-plus] 项目启动报错 (Issue #29)





 
fixed 为 true 的时候，正常 tabs 导航栏是不会动的，内容滚动，可能在迁移 ant design pro v5 的时候没注意样式变化，我晚些时间看看。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yunsii** [comment]
tabs 导航问题已修复 https://github.com/yunsii/ant-design-pro-plus/commit/21ddace5cbec558b970c6da3006d9f07fbd538d9

**Comment by yunsii** [comment]
close as stale.
