### ISSUE TITLE
history传参query操作路由后，跳转到的页面标签页出现异常

### ISSUE THREAD

**Issue by CementSealing** [yunsii/ant-design-pro-plus#34]
一个页面中有一个按钮，点击后history传参query操作路由跳转至另一个页面。当点击标签页进行跳转时，页面参数相同，但是会出现两个tab标签页。
![图片](https://user-images.githubusercontent.com/97492682/160732176-f7b5b5d8-5b50-4a20-aba9-05708f09ad6d.png)

**Comment by yunsii** [comment]
在线上 Demo 的查询页面 https://yunsii.github.io/ant-design-pro-plus/switch-tabs-demos/query 测试了一下，无法复现，你看看能复现吗？

**Comment by CementSealing** [comment]
> 在线上 Demo 的查询页面 https://yunsii.github.io/ant-design-pro-plus/switch-tabs-demos/query 测试了一下，无法复现，你看看能复现吗？

是基于参数路由的， `mode: Mode.Dynamic`。在查询页点击查询按钮跳转到结果页，`location.search` 是不带 `?` 的
，而点击结果页的标签页进行跳转，`location.search` 是带 `?` 的，请问这是正常的吗？
好像因为这个问号，在基于路由参数模式下，会导致生成的key值不同
![图片](https://user-images.githubusercontent.com/97492682/160743109-15a7551a-f60c-4c1c-8d54-1967d46d3543.png)
![图片](https://user-images.githubusercontent.com/97492682/160743187-723d5981-63e5-4dc4-8dd7-47e390bb23d3.png)

**Comment by yunsii** [comment]
看起来关系很大，我会争取今天内修复

**Comment by CementSealing** [comment]
> 看起来关系很大，我会争取今天内修复

还有个问题，就是 打开的标签页中有 ProTable，并配置了 `syncToUrl` 为true时，其它的标签页URL后面会自动添加上 `pageSize`  和 `current`  这两个参数。
` form={{
          syncToUrl: true
        }} `
![图片](https://user-images.githubusercontent.com/97492682/160784065-44bfad53-0ec2-4897-a7b2-c9f6a3170d2a.png)

**Comment by yunsii** [comment]
感谢反馈，今天统一看一下

**Comment by yunsii** [comment]
> 已修复 https://github.com/yunsii/use-switch-tabs/pull/3

升级到 `use-switch-tabs@0.1.4` 即可。另外 syncToUrl 的问题[这里](https://github.com/ant-design/pro-components/blob/master/packages/form/src/BaseForm/BaseForm.tsx#L190)导致的，[useUrlSearchParams](https://github.com/chenshuai2144/use-params/blob/master/src/index.ts#L37) 通过 `window.addEventListener('popstate', onPopState)` 会一直更新查询参数，这已经超出这个 hook 的能力范围了。因此，得看你的使用场景有没有必要还使用 syncToUrl 了，个人感觉好像不是很有必要，同时使用标签页和 syncToUrl 看起来有点奇怪。如果要方便分享加个按钮点击复制分享链接或许更方便？

当然如果一定要用，或许可以尝试仅在激活某个页面时候设置 syncToUrl 为 true 试试。这么一说的话好像得加一个判断 location 是否被激活的 API 才够方便 😂

**Comment by yunsii** [comment]
close as stale.
