### ISSUE TITLE
如何判断现在停留在哪个标签页？

### ISSUE THREAD

**Issue by CementSealing** [yunsii/ant-design-pro-plus#39]
请问要如何判断现在停留在哪个标签页？或者是在页面中判断是否停留在当前页面？

**Comment by yunsii** [comment]
之前在另一个讨论中谈到了这个问题，暂时还没添加，争取今天下班之后加上。另外问一下你这是准备用来干嘛呢？

**Comment by CementSealing** [comment]
> 之前在另一个讨论中谈到了这个问题，暂时还没添加，争取今天下班之后加上。另外问一下你这是准备用来干嘛呢？

有一个场景就是，从一个表格页面点击添加或者编辑按钮，进入添加或编辑页面，对数据进行修改，修改之后跳转到原表格页面。可能我对数据修改之前使用`ProTable`自带的`ProForm`进行了筛选，我希望跳转回来时数据刷新并保留开始选的筛选条件。使用`window.tabsAction.reloadTab()`进行标签页刷新那些筛选条件会没有。
