### ISSUE TITLE
如何再路由中设置，不要再页面中设置

### ISSUE THREAD

**Issue by changlin0501** [yunsii/ant-design-pro-plus#40]
![image](https://user-images.githubusercontent.com/47729295/165262273-3a799741-d274-427c-bad3-3ba21ac19609.png)

我的每个页面都有导出，所以我想再路由中使用多标签，请问该如何处理

**Comment by yunsii** [comment]
我都看不懂你这个提问……

**Comment by changlin0501** [comment]
> 我都看不懂你这个提问……
就是在page使用的时候能不能在其他地方实现，不用export default 去实现

**Comment by yunsii** [comment]
说得还是不明确，路由配置只是指定文件路径，文件在哪儿都可以，不知道是不是这个意思？

**Comment by changlin0501** [comment]
> 说得还是不明确，路由配置只是指定文件路径，文件在哪儿都可以，不知道是不是这个意思？

就是我将所有配置都配置好了，就差使用了，在页面使用时怎么都出现不了多标签 ，另外我想问问这种模式该处理使用呢：
基于路由，每个路由只渲染一个标签页

**Comment by yunsii** [comment]
默认就是这个模式，你是已有项目集成还是基于我这个项目的？

**Comment by changlin0501** [comment]
已有项目集成呢

**Comment by yunsii** [comment]
那还得看你是不是 ant design pro v5 了，这个需要加个 layout 层来拦截路由的，建议你搞个最小化的 demo 我可以帮你看看。

**Comment by changlin0501** [comment]
我是antd design pro V4

**Comment by yunsii** [comment]
https://github.com/yunsii/ant-design-pro-plus/blob/v4-legacy/src/layouts/BasicLayout.tsx#L172 没有最小化 demo 的话，我只能说看看 v4-legacy 分支的实现了。

**Comment by changlin0501** [comment]
> https://github.com/yunsii/ant-design-pro-plus/blob/v4-legacy/src/layouts/BasicLayout.tsx#L172 没有最小化 demo 的话，我只能说看看 v4-legacy 分支的实现了。

好的，我再看看，如有问题再向你请教，感谢

**Comment by changlin0501** [comment]
mode里面显示为undefined













在 2022-04-28 12:20:07，"云深" ***@***.***> 写道：

Closed #40.
