### ISSUE TITLE
在页面中使用不出现多标签栏是怎么回事，试了好多遍，不知道哪里出问题了

### ISSUE THREAD

**Issue by changlin0501** [yunsii/ant-design-pro-plus#41]
![image](https://user-images.githubusercontent.com/47729295/165672350-81008d1e-0e39-45d5-992d-9250922320c4.png)
![image](https://user-images.githubusercontent.com/47729295/165672459-21718a15-b174-47a1-a5bf-6857091e3391.png)

**Comment by yunsii** [comment]
给个简化的 Demo 啊，这看了也没用

**Comment by yunsii** [comment]
Close as stale
