### ISSUE TITLE
项目升级到umi4后,无法缓存页面

### ISSUE THREAD

**Issue by choby** [yunsii/ant-design-pro-plus#47]
项目升级到umi4后, 使用withSwitchTab方法无法阻止组件重新渲染, 也就导致每次切换回之前打开过的标签页, 页面内容会重新渲染. 不知道是我升级umi4的时候配置除了问题, 还是use-switch-tab组件本身兼容性的问题;
可以将项目升级到umi4进行测试一下然后告知处理方案吗? 谢谢.

**Comment by yunsii** [comment]
可以先看看这个讨论 https://github.com/yunsii/use-switch-tabs/issues/5

umi 4 开始使用 React Router 6 了，不是之前的方案了，后续会尝试跟进。
