### ISSUE TITLE
vite 是否可以配置 antd-vue 按需求加载

### ISSUE THREAD

**Issue by shiwanjun1995** [yunsii/ant-design-pro-plus#58]
https://github.com/vitejs/vite/issues/1389#issuecomment-876246617

你好，请教下：您说的楼上直接引用 CSS 的方式不能定制主题。具体是指什么意思？
我理解的是楼上大佬的插件【vbenjs/vite-plugin-style-import】
[https://github.com/vbenjs/vite-plugin-style-import/blob/main/README.zh_CN.md](https://github.com/vbenjs/vite-plugin-style-import/blob/main/README.zh_CN.md)

该插件的功能就是按需引入对应组件的样式。你是指的是这个插件只能动态引入（而不能动态修改）对应组件的默认样式这个意思对吗。

因为我现在想要做一个功能，就是动态切换整个项目的主题配色【就两种】。
1、第一想到的方案就是全部引入 antdvue 组件的深、浅样式，但是这样一来，样式文件的体积就很大了；
2、第二想到的方案是动态引入组件的深色或者浅色样式，这样一来，样式文件的体积就很小。
不知道该插件【vite-plugin-imp】是否能够满足动态引入组件样式。

**Comment by shiwanjun1995** [comment]
因为我现在使用的是 vite-plugin-style-import 组件，不知道 vite-plugin-imp 该组件是否即满足动态引入组件样式，又满足动态修改对应组件样式。

**Comment by yunsii** [comment]
之前都是纯静态导入的，这样的话除非样式是使用的 css variables 来配置以实现动态主题，否则都是通过引入不同的文件来实现的动态主题。

**Comment by yunsii** [comment]
另外，vue 的生态不是很了解，现在 antd v5 说是可以很方便的动态配置主题了，我也很久没使用 antd 了。

**Comment by shiwanjun1995** [comment]
感谢你的回复
1、你说的如果antdvue组件样式是否都是基于css变量，我感觉悬，具体点：比如a-menu等可配置主题组件它有theme【默认 dark】等属性可配置，其它诸如普通组件应该是基于css变量，可参考点为 ConfigProvider.
2、antd最新的版本看起来切换主题很方便，antdvue得赶紧给他提个feature.

**Comment by yunsii** [comment]
第一点我知道，之前都是纯静态的主题，之前的 ant design pro 支持运行时换主题我记得是编译的时候输出多份样式文件，通过文件切换的。antd vue 要跟上官方不知道得什么时候了，如果业务上不是很必要的话就生成一套符合当前设计的主题也可以吧。

**Comment by yunsii** [comment]
Closes as stale
