### ISSUE TITLE
问题：请问config/config.dev.ts是干嘛的？

### ISSUE THREAD

**Issue by NinthMonee** [yunsii/ant-design-pro-plus#60]
<img width="1221" alt="image" src="https://github.com/yunsii/ant-design-pro-plus/assets/47859908/2ca9cc26-1716-49cd-8a18-af2fc17d8d4a">
请问请问config/config.dev.ts是干嘛的？全局也没有搜到相关的config.dev.的使用痕迹，在antd pro文档中也没有config.dev文件的配置

**Comment by yunsii** [comment]
https://v3.umijs.org/zh-CN/docs/config#%E5%A4%9A%E7%8E%AF%E5%A2%83%E5%A4%9A%E4%BB%BD%E9%85%8D%E7%BD%AE 根据环境配置变量

**Comment by NinthMonee** [comment]
明白了，多谢解答
